trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'Npm install'
  inputs:
    command: install
    workingDir: src/TheFipster.Munchkin.Spa

- script: sudo npm install -g @angular/cli
  workingDirectory: src/TheFipster.Munchkin.Spa
  displayName: 'Install angular cli'

- script: sudo ng build --outputPath $(Build.ArtifactStagingDirectory)/publish/spa-client
  workingDirectory: src/TheFipster.Munchkin.Spa
  displayName: 'Build angular'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration)'

- script: dotnet test --filter FullyQualifiedName~UnitTest --logger trx --collect "Code coverage"
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Report test results'
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
    mergeTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish identity api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Identity.Api/TheFipster.Munchkin.Identity.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish gaming api'
  inputs:
    command: 'publish'
    projects: 'src/TheFipster.Munchkin.Gaming.Api/TheFipster.Munchkin.Gaming.Api.csproj'
    configuration: '$(BuildConfiguration)'
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish admin api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Admin.Api/TheFipster.Munchkin.Admin.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish cardstash api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.CardStash.Api/TheFipster.Munchkin.CardStash.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish statistics api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Statistics.Api/TheFipster.Munchkin.Statistics.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish sample api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Sample.Api/TheFipster.Munchkin.Sample.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish monitoring api'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Monitoring.Api/TheFipster.Munchkin.Monitoring.Api.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: DotNetCoreCLI@2
  displayName: 'Publish cli client'
  inputs:
    command: publish
    projects: src/TheFipster.Munchkin.Cli.Client/TheFipster.Munchkin.Cli.Client.csproj
    configuration: $(BuildConfiguration)
    zipAfterPublish: true
    publishWebProjects: false
    arguments: '--output $(Build.ArtifactStagingDirectory)/deploy'

- task: ArchiveFiles@2
  displayName: "Publish spa client"
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish/spa-client' 
    includeRootFolder: false 
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/deploy/TheFipster.Munchkin.Spa.Client.zip' 

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'apps'
    publishLocation: 'Container'