trigger:
- master
- feature/*

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DockerInstaller@0
  displayName: "Install docker cli"
  inputs:
    dockerVersion: '19.03.5'

- task: Docker@2
  displayName: "Build and push gaming_api container image"
  inputs:
    containerRegistry: 'Treescale'
    repository: 'orangecurtain/munchkin_apis_gaming'
    command: 'buildAndPush'
    Dockerfile: 'src/gaming_api.dockerfile'
    buildContext: '.'